### ISSUE TITLE
Package off CRAN for email bounce?

### ISSUE THREAD

**Issue by eddelbuettel** [nano-optics/rcppfaddeeva#5]
Going to https://cloud.r-project.org/package=RcppFaddeeva gets us 

> Package ‘RcppFaddeeva’ was removed from the CRAN repository.
>
> Formerly available versions can be obtained from the archive.
>
> Archived on 2022-05-23 as email to the maintainer is undeliverable.
>
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-05-23_check_results_RcppFaddeeva.html).
>
> Please use the canonical form https://CRAN.R-project.org/package=RcppFaddeeva to link to this page.

Seems like a pity the email bounces as the package appears to be in good standing otherwise.

**Comment by baptiste** [comment]
Oops, thanks for noticing – I had not seen this. Yeah, my former gmail account no longer exists, so I should really update the packages that still have it in the contact details. Will do ASAP.

**Comment by baptiste** [comment]
back on cran

**Comment by eddelbuettel** [comment]
Yes, thanks, I know as [CRANberries](https://dirk.eddelbuettel.com/cranberries/) told me when it happened. Good to close indeed and thanks for following up.
